version: '3.8'

volumes:
    redis_data:

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:6.0.9-alpine
    command:
      redis-server
    ports:
      - target: 6379
        published: 6380
        protocol: tcp
        mode: host
    volumes:
        - redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master

  celery:
    build: .
    command: celery -A short_urls worker --loglevel=INFO -E
    restart: always
    environment:
      - C_FORCE_ROOT=1
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
    hostname: celery-main

  celery-beat:
    build: .
    command: celery -A short_urls beat --loglevel=INFO --pidfile=
    restart: always
    volumes:
        - .:/code
    depends_on:
        - web
        - redis
    hostname: celery-beat

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/3
      - FLOWER_PORT=8888
    depends_on:
      - celery
      - celery-beat
      - redis
    restart: always
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host






