# Generated by Django 3.1.3 on 2020-11-02 18:22

import bitly.validators
from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='short_url',
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='url_code',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(7,), **{}), max_length=7, unique=True, verbose_name='short_url'),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='user_id',
            field=models.UUIDField(db_index=True, validators=[bitly.validators.UUIDValidator(4)], verbose_name='user unique identifier'),
        ),
    ]
