# Generated by Django 3.1.3 on 2020-11-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0002_auto_20201102_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='full_url',
            field=models.URLField(db_index=True, verbose_name='full url'),
        ),
    ]
