# Generated by Django 3.1.3 on 2020-11-03 09:19

import django.core.validators
from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0003_auto_20201103_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='url_code',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(7,), **{}), max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='short_url'),
        ),
        migrations.AddConstraint(
            model_name='urlmodel',
            constraint=models.CheckConstraint(check=models.Q(url_code__length=7), name='url_code_length_check'),
        ),
    ]
