# Generated by Django 3.1.3 on 2020-11-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0004_auto_20201103_1219'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='urlmodel',
            constraint=models.CheckConstraint(check=models.Q(user_id__regex='[0-9a-f]{12}4[0-9a-f]{3}[89ab][0-9a-f]{15}\\Z'), name='user_id_uuid_check'),
        ),
    ]
