# Generated by Django 3.1.3 on 2020-11-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0005_auto_20201103_1230'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='urlmodel',
            constraint=models.CheckConstraint(check=models.Q(full_url__regex='((https?):((//)|(\\\\\\\\))+[\\w\\d:#@%/;$()~_?\\+-=\\\\\\.&]*)'), name='full_url_check'),
        ),
    ]
