# Generated by Django 3.1.3 on 2020-11-03 14:56

import bitly.validators
import django.core.validators
from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0006_auto_20201103_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='full_url',
            field=models.URLField(error_messages={'invalid': 'URL не корректно отформатированн'}, verbose_name='full url'),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='url_code',
            field=models.CharField(db_index=True, default=functools.partial(django.utils.crypto.get_random_string, *(7,), **{}), error_messages={'max_length': 'Длинна "url_code" должна быть ровно 7 символов', 'min_length': 'Длинна "url_code" должна быть ровно 7 символов', 'unique': 'Такой "url_code" уже существует. Придумайте другой'}, max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='short_url'),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='user_id',
            field=models.UUIDField(db_index=True, error_messages={'invalid': 'Строка UUID не соответсует стандарту. Допустимы только строки UUID версии 4'}, validators=[bitly.validators.UUIDValidator(4)], verbose_name='user unique identifier'),
        ),
    ]
