# Generated by Django 3.1.3 on 2020-11-04 09:23

import django.core.validators
from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('bitly', '0007_auto_20201103_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='url_code',
            field=models.CharField(db_index=True, default=functools.partial(django.utils.crypto.get_random_string, *(7,), **{}), error_messages={'max_length': 'Длинна "url_code" должна быть ровно 7 символов', 'min_length': 'Длинна "url_code" должна быть ровно 7 символов', 'unique': 'Такой "url_code" уже существует. Придумайте другой'}, max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='url_code'),
        ),
    ]
